### ISSUE TITLE
Ask permission for Atomium

### ISSUE THREAD

**Issue by jorensjongers** [oSoc19/cycling-up-frontend#114]
Send email to copyright person of Atomium.
Use wording like:  ‘can you please confirm it you we can use it’ + mention we have 3 buildings in total.

**Comment by jbelien** [comment]
Let's wait for the answer before closing the issue :)

**Comment by danielleterras** [comment]
Beste,
 
De tekening mag gebruikt worden, zoals afgebeeld op uw site.
Is het mogelijk om ergens onze site (in plaats van de copyright) te vermelden? www.atomium.be
Alvast bedankt.
 
Met vriendelijke groeten,
 
Yvonne Boodts

Translation: We're good to go, just refer to www.atomium.be somewhere in the code that it's clear we have the right to use the image!
