### ISSUE TITLE
Add source links on each page

### ISSUE THREAD

**Issue by danielleterras** [oSoc19/cycling-up-frontend#121]

**Comment by cecilediana** [comment]
**Evolution Graph:** Source: Brussels Mobility (not hyperlink available, transmuted by Frederik) 
**How many people ride their bike to work? Graph:** Source: SPF Mobilité et Transports (Diagnostic des déplacements domicile-travail) URL:  http://ibsa.brussels/fichiers/chiffres/13.6_mobilite_transport_pratiques_deplacements.xls/view#.XTgJfC2B2YU
**Villo! Rental per year Graph:**  Source: JC Decaux
URL:  http://ibsa.brussels/fichiers/chiffres/13.2_mobilite_transport_mobilite_active.xls/view#.XTgKmS2B2YU
**Bike Count Graph:** Source: Bruxelles Mobilité (Observatoire du vélo en Région de Bruxelles-Capitale - Pro Velo asbl)
Link: http://ibsa.brussels/fichiers/chiffres/13.2_mobilite_transport_mobilite_active.xls/view#.XTgKmS2B2YU
