### ISSUE TITLE
Evolution slide: separate graph for infra and GFR

### ISSUE THREAD

**Issue by jorensjongers** [oSoc19/cycling-up-frontend#129]
The graph has to show to separate lines. One for the 'normal infra' and one for the GFR.

**Comment by jbelien** [comment]
Also don't forget to fix the chart !
Each "gap" should be the same amount of years !
Someone fixed this already in a previous commit !

---

This is wrong :

![Capture](https://user-images.githubusercontent.com/1150563/61795837-91d19d00-ae24-11e9-8370-381ed934b0c7.JPG)
