### ISSUE TITLE
List all available endpoints

### ISSUE THREAD

**Issue by jorensjongers** [oSoc19/cycling-up-frontend#16]
Dress a semi-complete list of the available endpoints on the API with their route, method and parameters.
Describe the constraints on the endpoints.

**Comment by Dakad** [comment]
## DESCRIPTION

Get the historical map by data

### URL :  /api/map/historical/?date=year

eg /api/map/historical/?date=1980


Get general map data

### URL: /api/map/general/kind
eg /api/map/general/bike_parking

Available kinds:

- bike_parking
- bike_shop
- bike_pump
- bike_infra

**Comment by jbelien** [comment]
https://api.cyclingup.osoc.be/api/doc
