### ISSUE TITLE
Slide with infrastructures/services map

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#66]
- [x] Map
- [x] Title
- [x] Text content
- [x] Design
- [x] Back-End providing data

---

Map should contain:

- [x] Cycle pumps
- [x] Bike sheds #25 #30 
- [x] Bike shops
- [x] Villo! stations #27  #32 
- [x] GFR #28 #33
- [x] Current infrasctructure ?

**Comment by jbelien** [comment]
Related issues: #40 #39 #38 #37 #33 #32 #31 #30

**Comment by cecilediana** [comment]
Title: Actual Map

**Comment by jorensjongers** [comment]
@jbelien I don't think the GFR network should be the base layer here. I remember the client saying in the meeting that they would like to see the live bike count 'bubbles' on top of the GFR network. So as to show that the infrastructure that is provided is actually used.

**Comment by jbelien** [comment]
@jorensjongers You're right, I confused the 2 slides!
I move the GFR "baselayer" to #67

**Comment by jbelien** [comment]
I see that "Text content" checkbox is checked. @cecilediana Could you copy-paste the content of this slide here ?

**Comment by cecilediana** [comment]
Text: The data displayed on the map reflects the actual bicycle infrastructures in the Brussels region. It comprises the cycle pumps locations, bike sheds, bike shops and Villo! stations.
