### ISSUE TITLE
Slide with bike count map + chart

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#67]
- [x] Map
    - [x] Should have GFR network as "baselayer"
- [x] Chart
- [x] Title
- [x] Text content
- [x] Design
- [x] Back-End providing data
-- live data + GFR: Done
-- Todo: historical data
- [x] Connect to the API

---

**Live API:** https://data-mobility.brussels/bike/api/counts/
**Live API with location:** http://data-mobility.brussels/geoserver/bm_bike/wfs?service=wfs&version=1.1.0&request=GetFeature&srsName=EPSG:4326&outputFormat=json&typeName=bm_bike:rt_counting

**Comment by cecilediana** [comment]
Graph type: Histogram

**Comment by cecilediana** [comment]
Title: "Current number of cyclists"

**Comment by cecilediana** [comment]
Text: Based on the Regional Cyclable Itineraries (RCI or as well known as the ICRs or GFRs), this map displays  the actual number of cyclists according to these cyclable paths. Over the day, the number of cyclists evolves and is shown through larger to smaller circles.
