### ISSUE TITLE
Slide with Villo! stations

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#70]
- [x] Chart
- [x] Title
- [x] Text content
- [x] Design
- [x] Back-End providing data
- [x] Connect to the API

---

**API:** https://opendata.bruxelles.be/explore/dataset/stations-villo-disponibilites-en-temps-reel/information/

**Comment by cecilediana** [comment]
Title: "Villo! Users"

**Comment by cecilediana** [comment]
Graph type: "line"

**Comment by cecilediana** [comment]
Text: "Villo! is a rental programme run in the region of Brussels capital. It aims at enhancing and encouraging sustainable mobility to citizens. Bikes can be rented out from the actual 360 existing stations. The graph displays the total amount of Villo! users recorded from 2010 till 2017. The steady rise between this period of time is related to the increasing demand as well as the rise of the number of stations available."

**Comment by jbelien** [comment]
⚠️ Apparently the https://opendata.bruxelles.be/ API is not up-to-date ; see #126 !
