### ISSUE TITLE
Slide with commute to work

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#71]
- [x] Chart
- [x] Title
- [x] Text content  
- [x] Design
- [ ] Back-End providing data

**Comment by cecilediana** [comment]
Title: "Home to Work by Bicycle"

**Comment by cecilediana** [comment]
Chart: "Histogram"

**Comment by cecilediana** [comment]
Citizens using bikes to commute to work within Brussels city increased from 2005 (1.2%) till 2017 (4.4%). This rise shows an augmentation in the demand for sustainable solutions when moving from home to work. Hence, the melioration of bikes infrastructures within the Brussels region enhance this steady increase.

**Comment by jbelien** [comment]
Need data from back-end (ping @jorensjongers)

**Comment by jbelien** [comment]
Fix the x axis of the chart : every step has to be the same "duration" !

**Comment by jbelien** [comment]
Fix the responsiveness of the chart
