### ISSUE TITLE
All data processing in one process_data process

### ISSUE THREAD

**Issue by jorensjongers** [oSoc19/cycling-up-frontend#97]
Make all data processing processes as found in process_data run at the same time and clean up folder structure.

**Comment by Dakad** [comment]
@jorensjongers 
## Steps
1. Create a data folder at the root of the project folder
2. Create folder**S** for each type of data
3. Add more data DIR variables into `Config.py`
4. Use the Config data DIR var in each files using the string version in the `open()` function
